name: goalign_dedup
description: Deduplicate sequences that have the same sequence
keywords:
    - alignment
tools:
    - goalign:
        description: |
            Goalign is a set of tools to handle sequence alignments.
        homepage: https://github.com/evolbioinfo/goalign
        documentation: https://github.com/evolbioinfo/goalign/blob/master/docs/index.md
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.

input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - aln:
        type: file
        description: A multi-sequence alignment file
        pattern: "*.{afa,fasta,phy,clustal,nex}"

output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - aln:
        type: file
        description: A deduplicated alignment file
        pattern: "*.{bam,cram,sam}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@andersgs"
