name: nwutil_order
description: Orders nodes according to various criteria, preserving topology.
keywords:
    - phylogenetic trees
tools:
    - nwutil:
        description: |
            The Newick Utilities are a suite of Unix shell tools for processing phylogenetic trees. 
        homepage: https://github.com/tjunier/newick_utils
        documentation: https://github.com/tjunier/newick_utils/wiki
        doi: 10.1093/bioinformatics/btq243
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.

input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - nwk:
        type: file
        description: A phylogenetic tree in newick format
        pattern: "*.{nwk}"

output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - nwk:
        type: file
        description: A newick tree file with re-ordered nodes
        pattern: "*.{nwk}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@andersgs"
